# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-US"
title: "chambers.io"
email: dakotachambers@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Technical writing and miscellaneous thoughts on software development, Linux, automation, and everything DevOps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chambers.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dakotachambers
github_username: dcchambers

# Build settings
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
remote_theme: "mmistakes/minimal-mistakes"
#theme: minima
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Site Author
author:
  name: "Dakota Chambers"
  bio: "I'm a software engineer focused on devops and automating boring things!"
  avatar: "/assets/images/dakota_avatar.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  location: "Madison, WI"
  twitter: dakotachambers
  github: dcchambers
  linkedin: dakota-chambers
  links:
    - label: "omg.lol"
      icon: "fas fa-fw fa-heart"
      url: "https://dakota.omg.lol"
    - label: "RSS/Atom Feed"
      icon: "fas fa-fw fa-rss-square"
      url: "/feed.xml"
    - label: "Bluesky"
      icon: "fas fa-fw fa-brands fa-bluesky"
      url: "https://bsky.app/profile/chambers.io"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: # true
      comments: true
      share: # true
      related: # true
      show_date: true

# Giscus Comments
repository: dcchambers/dcchambers.github.io
comments:
  provider: "giscus"
  giscus:
    repo_id: MDEwOlJlcG9zaXRvcnk1NjYyMTg3MQ==
    category_name: "Blog Comments"
    category_id: DIC_kwDOA1_7L84CVBFQ
    discussion_term: pathname
    reactions_enabled: 1
    theme: "light"

include:
  - _pages

#minimal-mistakes specific
paginate: 99 # amount of posts to show on home page.
paginate_path: index.md

## Jekyll Feed config
feed:
  posts_limit: 100
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
